### ISSUE TITLE
Tell Your Exchange

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/MyvoteEOS-proxy#18]
![image](https://user-images.githubusercontent.com/5632966/150167648-437ef567-41b0-4fca-a2f7-e369d8554bc3.png)

Generate tweet and count mentions

**Comment by leisterfrancisco** [comment]
@xavier506 is there a template for the tweet we want?

**Comment by xavier506** [comment]
Lets make it something simple like this to start 

```
@exchangeTwitter I own my vote and urge you to support #Myvoteeos 
```
