### ISSUE TITLE
Link Google Forms

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/MyvoteEOS-proxy#28]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/5632966/152835255-ae631cc0-a342-4712-9e14-73b02f574c43.png">

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/5632966/152835326-fd600e7c-6fc7-4b8d-9315-b7fa715c4cb6.png">

 BP Application Form: https://docs.google.com/forms/d/e/1FAIpQLScLQHUtZrx8JMdVhk32x0rIEh78t4HkdplxcbTG0f7UoTRR7w/viewform

**Comment by leisterfrancisco** [comment]
@xavier506 could you add a description to this task, please.
