### ISSUE TITLE
Blank screen after voting for proxy

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/MyvoteEOS-proxy#65]
I get a blank screen after voting for a proxy

![image](https://user-images.githubusercontent.com/5632966/153073091-24a48db0-c915-4111-8085-a12d7d5978f4.png)

**Comment by leisterfrancisco** [comment]
@xavier506 which browser did you test it? I don't get that error.

![image](https://user-images.githubusercontent.com/28828796/153403923-97abe291-0494-4a68-ac0c-14fa9f8b01b8.png)
