### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/MyvoteEOS-proxy#68]

**Comment by hahnryu** [comment]
Where can I have json?

**Comment by xavier506** [comment]
webapp/src/language/en.json

**Comment by xavier506** [comment]
{
  "translations": {
    "login": "Login",
    "home": "Home",
    "news": "News",
    "bPs": "BPs",
    "about": "About",
    "exchanges": "Exchanges",
    "eosHolder": "Holders",
    "htmlTitle": "MyvoteEOS Proxy",
    "homeTitle": "Welcome to MyvoteEOS Proxy",
    "newsTitle": "EOS News",
    "logout": "Logout",
    "joinCommunity": "Join the community",
    "copyRight": "COPYRIGHT © 2022 SH CO. LTD. ALL RIGHTS RESERVED.",
    "myVoteEos": "#MyvoteEOS",
    "blog": "Read our blog",
    "twitter": "Follow us on Twitter",
    "discord": "Connect on Discord",
    "telegram": "Chat on Telegram",
    "litepaper": "Litepaper",
    "deck": "Intro Deck",
    "quicklinks": "Quicklinks",
    "social": "Social",
    "assets": "Assets",
    "success": "success"
  },
  "homePage": {
    "htmlTitle": "MyvoteEOS Proxy",
    "headerTitle": "Secondary Title",
    "secondaryText": "Reestablish legitimacy and accountability in blockchain governance by uncompromised consensus of all EOS holders on and off chain.",
    "myVoteEos": "#MyvoteEOS",
    "downloadButton": "Download intro PDF",
    "joinAlliance": "Join the Alliance",
    "tellExchange": "Tell Your Exchange",
    "delegateVote": "Delegate Your Vote",
    "joinMovement": "Join the Movement",
    "placeholder": "Enter your email to join the movement and receive intro PDF.",
    "join": "Join",
    "whatIsNVB": "What is MyvoteEOS proxy",
    "why": "Why?",
    "myVoteProxy": "#MyvoteEOS proxy",
    "keepBps": "Keeping BPs Accountable",
    "legitimacy": "Legitimacy",
    "accountability": "Accountability",
    "interestAlignment": "Interest Alignment",
    "selectionCriteria": "Voting Principle",
    "eligibility": "Only those BPs who join the #MyvoteEOS Alliance by signing the pledge below will be considered for vote:",
    "joinTitle": "BPs in the Alliance",
    "exchangeStatus": "Exchange Status",
    "twitToUrge": "Tweet to urge them",
    "participating": "Participating EOS members",
    "supportPartner": "Partners and Contributors",
    "homeText": {
      "joinLabel": "Join the movement and receive intro PDF deck.",
      "text1": "Are you a BP?",
      "text2": "Do you keep your EOS on centralized exchanges?",
      "text3": "Are you an on-chain account holder?",
      "text4": "BPs joined the alliance",
      "text5": "# of mentions on Twitter",
      "text6": "Holders delegating their vote",
      "text7": "The EOS based proxy facilitates the transition into a truly democratic based chain that is free from Pareto control by voting for BP’s that do not engage with direct vote rebate.",
      "text8": "EOS came with the vision of becoming a governed blockchain.",
      "text9": "But without no-vote-buy rule, DPoS isn’t much different than all PoW or PoS in which the consensus is captured by the pareto distribution.",
      "text10": "EOS is on the verge of becoming the only blockchain that is free from the grip of pareto distribution with fractal democracy.",
      "text11": "But it needs support from the BPs.",
      "text12": "MyvoteEOS Proxy is an EOS BP voting proxy that aims to properly represent the uncompromised will of EOS holders on and off chain.",
      "text13": "The baseline function of MyvoteEOS Proxy is to ensure the integrity of its vote and the accountability of BPs representing communities' will for the votes they receive. This will be achieved through holding regular check-up calls with BPs and reviewing reports of their finances and activities.",
      "text14": "OneDAO proxy will only votes from among the list that passes the integrity bar.",
      "text15": "Heal the governance with greater alignment of interests",
      "text16": "We will not engage in vote compromise in any form. (operating our own proxy with direct APR, buying votes from 3rd party exchanges or proxies.)",
      "text17": "We will commit to being held accountable by engaging in check up calls and providing public financial and operation reports on a regular basis.",
      "text18": "We acknowledge that we can be unvoted immediately and won’t be eligible for votes from this DAO ever again if we engage with compromised votes hereafter."
    }
  }
}
