### ISSUE TITLE
MyvoteEOS website last minor feedback

### ISSUE THREAD

**Issue by hahnryu** [eoscostarica/MyvoteEOS-proxy#76]
@xavier506 @tetogomez 

I think this is the last minor feedback about the website. I think we're now stable with the branding and content, I think we're good to go for translation. It won't take too long. I'll begin ASAP. If you can give me all language JSON files (for ES, EN, CH, KO), I'll delegate to get all them translated.

Your work counts! 
Thank you so much! :)
Hahn

For the attachment, please check the Discord global org channel.

**Comment by xavier506** [comment]
json files are located here, use the english file as reference

https://github.com/eoscostarica/MyvoteEOS-proxy/tree/dev/webapp/src/language
